SELECT [RamacRequestID]
      ,[RequestID]
      ,[RAMAC]
      ,[DateTimeInserted]
      ,[DateTimeUpdated]
      ,[Instr]
      ,[ToolOrderID]
      ,[MESFlag]
      ,[UpdatedByBEMSID]
  FROM [TEDArLog].[dbo].[RamacRequest]