SELECT [mesUserID]
      ,[BemsID]
      ,[Name]
      ,[BluesStatus]
      ,[Phone]
      ,[Budget]
      ,[Building]
      ,[StableAddress]
      ,[ManagerName]
      ,[DepartmentName]
      ,[MailCode]
  FROM [TEDTLC].[dbo].[MES_Employee]