SELECT o.[OrderID]
      ,o.[ToolSeries_ToolCode_ToolNumber]
      ,o.[INSPTYPE]
      ,o.[OperNo]
      ,o.[Operation_Description]
      ,o.[SCHEDULED_START_DATE]
      ,o.[DateStartPlan_Mday]
      ,o.[SCHEDULED_COMPLETE_DATE]
      ,o.[DateCompPlan_Mday]
      ,o.[PLAN_STATUS]
      ,o.[Setup_Time]
      ,o.[Run_Time]
      ,o.[TotEstmOp]
      ,o.[WorkCenter]
      ,o.[WorkArea]
      ,o.[WorkLoc]
      ,o.[WPA_NUMBER]
      ,o.[Unit]
      ,o.[TOOLNUMBER]
      ,o.[SERIES]
      ,o.[ToolCode]
      ,o.[Revision_Number]
      ,o.[Part_Key]
      ,o.[Operation_Key]
  FROM [TEDTLC].[dbo].[MES_CAPP_ToolOrder_Complete] i
  JOIN [TEDTLC].[dbo].[MES_CAPP_OperationData_Complete] o
    ON o.[Part_Key] = i.[PART_KEY]
 WHERE i.[SiteCD_LOC] = 'WA016'