SELECT NC_REC_CLS_CD,
  	   NC_ORIG_LOG_CO_CD,
	   NC_SEQ_ID,
	   NC_KEY,
	   QD_NC_SEQ_NO,
	   LAST_UPD_DT,
	   LAST_UPD_TM,
	   REC_TYP_CD,
	   Q_ID,
	   REV_NO,
	   ENQ_DT,
	   ENQ_TM,
	   ENQ_CD,
	   Q_TSK_SEQ_NO,
	   LOG_CO_CD,
	   AR_CD,
	   SUB_AR_CD,
	   TSK_CD,
	   Q_STAT_CD,
	   ASGND_TO_NM,
	   FST_CHK_OUT_DT,
	   FST_CHK_OUT_TM,
	   US_NM,
	   US_ORG_ID,
	   US_PH_ID,
	   US_ID,
	   CHK_OUT_DT,
	   CHK_OUT_TM,
	   EXIT_DT,
	   EXIT_TM,
	   EXIT_CD,
	   DLET_PATH_IND,
	   NARR_PSEUDO_NO,
	   INIT_DT,
	   INIT_TM,
	   INIT_NM,
	   INIT_ORG_ID,
	   INIT_PH_ID,
	   CHK_OUT_DEVICE_ID,
	   HH_UPD_DT,
	   HH_UPD_TM 
 FROM NCMV.QD_NC
WHERE NC_ORIG_LOG_CO_CD = '142'
  AND INIT_DT between (date - interval '3' year) and date