SELECT [PMDoc_ID]
      ,[ToolType]
      ,[ToolNumber]
      ,[Model]
      ,[Type2Hr]
      ,[Type3Hr]
      ,[Hoist]
      ,[BTH]
      ,[MCG]
      ,[CTM]
      ,[ToolDesc]
      ,[Remarks]
      ,[CreateBEMSId]
      ,[CreateDt]
      ,[EditBEMSId]
      ,[EditDt]
      ,[DocStatus]
      ,[RevId]
      ,[TTORev]
      ,[ApprovalStatus]
      ,[ComplexTool]
      ,[MigInd]
      ,[CreatedByName]
  FROM [TIPS].[dbo].[PMDoc]
